name: Deploy Job to Google Cloud Run

on:
  workflow_run:
    workflows: ["Deploy to Google Cloud Run"]
    branches: [master]
    types: [completed]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  JOB_NAME: moxalise-data-transfer
  SCHEDULER_NAME: moxalise-data-transfer-scheduler
  REGION: europe-west3
  REPOSITORY: moxalise-api
  SERVICE_NAME: moxalise-api

jobs:
  deploy-job:
    name: Deploy to Cloud Run Jobs
    runs-on: ubuntu-latest
    # Only run this job when the workflow run event is a success
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Deploy to Cloud Run Jobs
        run: |
          # Deploy (create or update) the Cloud Run job
          gcloud beta run jobs deploy $JOB_NAME \
            --image $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE_NAME:${{ github.sha }} \
            --region $REGION \
            --set-env-vars=JOB_NAME=transfer_data \
            --memory=1Gi \
            --cpu=1 \
            --max-retries=3 \
            --task-timeout=5m \
            --parallelism=1

      - name: Update Cloud Scheduler Job
        run: |
          # Check if scheduler job exists, delete if it does
          if gcloud scheduler jobs describe $SCHEDULER_NAME --location=$REGION 2>/dev/null; then
            echo "Scheduler job exists, deleting"
            gcloud scheduler jobs delete $SCHEDULER_NAME --location=$REGION --quiet
          fi
          
          # Create Cloud Scheduler job
          gcloud scheduler jobs create http $SCHEDULER_NAME \
            --schedule="*/5 * * * *" \
            --location=$REGION \
            --uri="https://$REGION-run.googleapis.com/apis/run.googleapis.com/v1/namespaces/$PROJECT_ID/jobs/$JOB_NAME:run" \
            --http-method=POST \
            --oauth-service-account-email=$PROJECT_ID@appspot.gserviceaccount.com \
            --oauth-token-scope=https://www.googleapis.com/auth/cloud-platform \
            --attempt-deadline=4m30s